name: Lint Python Code

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest  # you can also use matrix if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.3'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 app.py
